### ISSUE TITLE
Possibilty to add HEIC delegate to ImageMagick 

### ISSUE THREAD

**Issue by cyrille-sg** [Scalingo/ruby-buildpack#17]
Could it be possible to change the compilation flags of ImageMagick in the base image in order to be able to add the delegate HEIC in order to have a image storage process that in more efficient from an size point of view

**Comment by Soulou** [comment]
Currently, we're using the compiled version of ImageMagick from Ubuntu repository, and we won't change it for now. This issue will have to be handled through a custom buildpack compiling ImageMagick from source, or downloading a pre-compiled version with HEIC support.

Plus, this has nothing to do in the ruby buildpack (this buildpack is not responsible for installing ImageMagick) ;-)

A cusom heroku buildpack does exist for this purpose: https://github.com/HiMamaInc/heroku-buildpack-imagemagick-heif
