### ISSUE TITLE
Add Ruby patch 2.2.9, 2.3.6, and 2.4.3

### ISSUE THREAD

**Issue by nicolasleger** [Scalingo/ruby-buildpack#3]
- https://www.ruby-lang.org/en/news/2017/12/14/ruby-2-2-9-released/
- https://www.ruby-lang.org/en/news/2017/12/14/ruby-2-3-6-released/
- https://www.ruby-lang.org/en/news/2017/12/14/ruby-2-4-3-released/

- https://devcenter.heroku.com/changelog-items/1346

**Comment by Soulou** [comment]
Thanks, support will be added quickly

**Comment by Soulou** [comment]
Version support added http://changelog.scalingo.com/
