### ISSUE TITLE
Support Ruby 3.3.0

### ISSUE THREAD

**Issue by ssaunier** [Scalingo/ruby-buildpack#56]
Ruby 3.3.0 has been [released](https://www.ruby-lang.org/en/news/2023/12/25/ruby-3-3-0-released/), I guess we need to wait for heroku/heroku-buildpack-ruby#1412 to be merged to backport it here in this buildpack.

Merry christmas to the Scalingo team 🎅 !

**Comment by guillaumewrobel** [comment]
🎅 

![CleanShot 2023-12-26 at 11 59 42@2x](https://github.com/Scalingo/ruby-buildpack/assets/20317297/7399dc47-c4b0-4e67-8560-55967bd6694d)

**Comment by ipfaze** [comment]
Hello there :wave: 
Thanks for your issue, we are handling it.
Happy holiday season :santa: !
