### ISSUE TITLE
Sync with upstream (from v268 to v270)

### ISSUE THREAD

**Issue by EtienneM** [Scalingo/ruby-buildpack#65]
Notify when done: 
- https://app.intercom.com/a/inbox/w4oogu7s/inbox/shared/all/conversation/12375700237027?view=List
- https://app.intercom.com/a/inbox/w4oogu7s/inbox/shared/all/conversation/12375700237449?view=List

This includes Ruby 3.3.1.

**Comment by guillaumewrobel** [comment]
any news @Frzk @EtienneM?
